### ISSUE TITLE
Sending messages

### ISSUE THREAD

**Issue by murkle** [oddpetersson/gocube-protocol#1]
Is there a header or checksum needed when sending messages eg EnableOrientation 0x38 ?

(For Go Dice, you just send one byte but I can't get that to work with GoCube)

**Comment by oddpetersson** [comment]
No header or checksum necessary. Here is a quick and dirty python script that:

- connects
- enable notifications
- disable orientation messages
- request battery status
- enable orientation messages

On my Mac i need to run the script a couple of times before it is able to connect..

    #!/usr/bin/env python3
    
    import asyncio
    from bleak import BleakScanner, BleakClient
    import json
    
    uuid_rx = '6e400002-b5a3-f393-e0a9-e50e24dcca9e'
    uuid_tx = '6e400003-b5a3-f393-e0a9-e50e24dcca9e'
    
    def notify_callback(handle, data):
        print('notify:', handle, data)
    
    async def main():
        gocube_device = None
    
        devices = await BleakScanner.discover()
        for device in devices:
            if device.name is not None and device.name[0:6] == 'GoCube':
                print('found:', device)
                gocube_device = device
            else:
                print('ignoring:', device)
    
        if gocube_device is None:
            print('no gocube found. try again.')
            return
    
        print('\nconnecting to:', gocube_device.name)
    
        async with BleakClient(gocube_device.address) as client:
    
            print('\nenable notifications')
            await client.start_notify(uuid_tx, notify_callback)
            await asyncio.sleep(1)
            print('\ndisable orientation')
            await client.write_gatt_char(uuid_rx, b'\x37', False)
            await asyncio.sleep(1)
            print('\nrequest battery')
            await client.write_gatt_char(uuid_rx, b'\x32', False)
            await asyncio.sleep(1)
            print('\nenable orientation')
            await client.write_gatt_char(uuid_rx, b'\x38', False)
            await asyncio.sleep(1)
            await client.stop_notify(uuid_tx)
    
    
    asyncio.run(main())

**Comment by murkle** [comment]
Thanks so much! Got it working: https://murkle.github.io/utils/webbluetooth/GoCube.html

(I've only got a 2x2 cube, there are some differences in what's sent)

**Comment by oddpetersson** [comment]
Excellent!
